print('jamón y queso')
#print('doesn't')
print('doesn\'t')
print("'doesn't")
print("jajajajajajajajajaajajajajajajaj")
print('"si, "le dijo"')
print("\"si, \"le dijo")
print('"isn\'t," she said')
print('doesn\'t')
